### ISSUE TITLE
Static objects have constant blur when in FSR 2.2

### ISSUE THREAD

**Issue by rbwldrf** [sphynx-owner/JFA_driven_motion_blur_addon#3]
I've been trying to implement this, but when I have a static object rendered by a static camera, the static object has a constant blur pointing up and to the left. 

![Screenshot 2024-07-10 at 00 44 36](https://github.com/sphynx-owner/JFA_driven_motion_blur_addon/assets/53384860/60c81d3f-ab64-45c4-bd57-25a13badc33b)

~~I managed to circumvent this issue by creating a "vibrator" class for all my world objects, where the position is altered by an insignificant amount (0.00001, could probably go lower, but doesn't seem noticeable to me)~~ Disregard this, it doesn't do anything to fix the issue.

**Comment by rbwldrf** [comment]
OK, so apparently this is an issue with FSR 2.2? Because I was switching between them, and it was working fine in FSR 1.0, but in 2.2, it freaks out.

**Comment by sphynx-owner** [comment]
This is a know issue and will be fixed in the future.

**Comment by sphynx-owner** [comment]
solved with latest commit
