### ISSUE TITLE
I dont understand, (not working)

### ISSUE THREAD

**Issue by sinaSPOGames** [sphynx-owner/JFA_driven_motion_blur_addon#6]
No matter where i put the Compositor or whatever Blur type i use nothing happens in my game

**Comment by sinaSPOGames** [comment]
[Video](https://youtu.be/5c1uGzT8EAA)

in this clip its supposed to do motion blur but only radial blur works. Not sure why
i added the compositor to Env didint work tried it with the Player Camera same result so... idk what to say atp

**Comment by sinaSPOGames** [comment]
okay so i think i found the problem, when using multiple camera the compositor doesnt work properly and only works one frame when switching cameras... why

**Comment by sphynx-owner** [comment]
https://github.com/user-attachments/assets/3ce8afa7-85c6-4576-9082-82aa8f6625b1

here I am able to switch between cameras by setting their 'current' property interchangeably. Basic motion blur setup on the environment.

I am not sure why this is happening to you. Note that there is also a connection to antialiasing methods and multisampling methods.

Now that I think of it, the most obvious candidate to why the motion blur does not work can be any transparent geometry that sits in front of your camera and overrides the velocity buffer, like the rain on glass effect that you have there. Best way to test this is by enabling the debug features and setting the debug option on your shader and pre-blur-processor shader and then add a debug compositor stage and setting its draw debug to enabled:
![image](https://github.com/user-attachments/assets/b9aac2d6-50b8-4036-9666-dfe9e0501aa2)

if You dont see any velocity buffer like data looking like this:
![image](https://github.com/user-attachments/assets/d532e8d9-e7c6-4f1c-9740-8844ed288866)

and its just black, then you may have something in the way.

its just a guess it could definitely also be a bug in the effect. for more support I suggest going to the shaders and vfx discord and reaching out in the wg-motion-blur channel. I am more available there.

https://discord.gg/NadW6SPj

**Comment by sinaSPOGames** [comment]
Hey! Thanks for replying 
Well I think I set up the thing wrong at first I just added the jumping blur without the pre motion thing (currently I'm not on my pc so I don't really remember the names) but this is what I have right now it works like a charm

Thanks

You might want to add some extra information about the setup tho at first I was so confused 

[That's how it looks like after the fix](https://youtu.be/usFQxRfJRdw?si=iPf-MPsIu92wqlkg)

**Comment by sphynx-owner** [comment]
I am glad you got it working. For your information I have added pretty detailed instructions in the README of this repo which you can look at on the github page. 

In addition, I do not recommend any of the jump flood motion blurs and instead going with Guertin motion blur, as it is the best overall.
